name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize, labeled]

jobs:

  claude-review:    
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@rc
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
 
      - name: Run Claude Code Review
        # Optional: Filter by PR author
        if: ${{ github.event.label.name == 'review required' }}
        id: claude-review
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          
          # Optional: Specify model (defaults to Claude Sonnet 4, uncomment for Claude Opus 4)
          # model: "claude-opus-4-20250514"
          
          # Direct prompt for automated review (no @claude mention needed)
          direct_prompt: |
            Please review this pull request on the basis of CLAUDE.md file.
         